// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9aMt3wwm5I93fAKcuB-uR93Mkcm5wTPI',
    appId: '1:93176661199:web:ca710b7f3e8e439a3be3ba',
    messagingSenderId: '93176661199',
    projectId: 'skill-trader-app-flutter',
    authDomain: 'skill-trader-app-flutter.firebaseapp.com',
    storageBucket: 'skill-trader-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG4PIbxf4ObPg1Gr6fETnbf5ZYgAZKQQI',
    appId: '1:93176661199:android:ecd535039cf5d7193be3ba',
    messagingSenderId: '93176661199',
    projectId: 'skill-trader-app-flutter',
    storageBucket: 'skill-trader-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiyK29ehtp-oYyqwsZU5KnzTbUn3-3sR4',
    appId: '1:93176661199:ios:03e630b067c159cc3be3ba',
    messagingSenderId: '93176661199',
    projectId: 'skill-trader-app-flutter',
    storageBucket: 'skill-trader-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.skillTraderAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiyK29ehtp-oYyqwsZU5KnzTbUn3-3sR4',
    appId: '1:93176661199:ios:03e630b067c159cc3be3ba',
    messagingSenderId: '93176661199',
    projectId: 'skill-trader-app-flutter',
    storageBucket: 'skill-trader-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.skillTraderAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9aMt3wwm5I93fAKcuB-uR93Mkcm5wTPI',
    appId: '1:93176661199:web:8dbb2262ec1241b63be3ba',
    messagingSenderId: '93176661199',
    projectId: 'skill-trader-app-flutter',
    authDomain: 'skill-trader-app-flutter.firebaseapp.com',
    storageBucket: 'skill-trader-app-flutter.firebasestorage.app',
  );

}